### ISSUE TITLE
1_finding_candidates

### ISSUE THREAD

**Issue by demonsec666** [wietze/windows-dll-hijacking#1]
No csv generated

**Comment by wietze** [comment]
I'm assuming you're talking about the CSV scripts generated in phase 1. Are you running everything from `c:\users\public\downloads\`?

**Comment by demonsec666** [comment]
Sorry, is it a problem with my steps?
![image](https://user-images.githubusercontent.com/24873495/86301674-04ecb180-bc39-11ea-8d7b-4337a3efd87c.png)

**Comment by wietze** [comment]
Something seems to go wrong in the step in which you run `python .\generate_pmc_files.py`, after running that your folder should be full of `*.pmc` files. Can you check if you're using python3?

**Comment by demonsec666** [comment]
thx
